import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fafaf1',
        'surface-dim': '#dadad2',
        'surface-bright': '#fafaf1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4ec',
        'surface-container': '#eeeee6',
        'surface-container-high': '#e9e9e0',
        'surface-container-highest': '#e3e3db',
        'on-surface': '#1a1c17',
        'on-surface-variant': '#4e4444',
        'inverse-surface': '#2f312c',
        'inverse-on-surface': '#f1f1e9',
        outline: '#807474',
        'outline-variant': '#d2c3c3',
        'surface-tint': '#6a5b5b',
        primary: '#261a1a',
        'on-primary': '#ffffff',
        'primary-container': '#3c2f2f',
        'on-primary-container': '#a99696',
        'inverse-primary': '#d6c2c1',
        secondary: '#b7102a',
        'on-secondary': '#ffffff',
        'secondary-container': '#db313f',
        'on-secondary-container': '#fffbff',
        tertiary: '#002030',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00364e',
        'on-tertiary-container': '#00a5e3',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#f3dedd',
        'primary-fixed-dim': '#d6c2c1',
        'on-primary-fixed': '#241919',
        'on-primary-fixed-variant': '#524343',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b1',
        'on-secondary-fixed': '#410007',
        'on-secondary-fixed-variant': '#92001c',
        'tertiary-fixed': '#c6e7ff',
        'tertiary-fixed-dim': '#83cfff',
        'on-tertiary-fixed': '#001e2d',
        'on-tertiary-fixed-variant': '#004c6b',
        background: '#fafaf1',
        'on-background': '#1a1c17',
        'surface-variant': '#e3e3db',
      },
      fontFamily: {
        sans: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        baseline: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '0px',
      },
      keyframes: {
        slideUpFade: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        rhythmicPulse: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.02)' },
        },
        markerPulse: {
          '0%': { transform: 'scale(0.8)', boxShadow: '0 0 0 0 rgba(183, 16, 42, 0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 10px rgba(183, 16, 42, 0)' },
          '100%': { transform: 'scale(0.8)', boxShadow: '0 0 0 0 rgba(183, 16, 42, 0)' },
        },
        'shimmer-scan': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        slideUpFade: 'slideUpFade 0.4s ease-out forwards',
        rhythmicPulse: 'rhythmicPulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        markerPulse: 'markerPulse 1.5s infinite',
        'shimmer-scan': 'shimmer-scan 2s linear infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
